name: C/C++ CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: |
        sudo apt update
        sudo apt install mm-common g++-11
        export CXX=g++-11
        cmake .
    - name: make
      run: |
       export CXX=g++-11
       make
    - name: run_tests
      run: |
        pwd
        ctest --output-on-failure
